using System;
using System.Collections.Generic;

namespace Currency
{
    public class CurrencyInfo
    {
        public string Code { get; set; }
        public double Rate { get; set; }

        class CountryInfo
        {
            public string Name { get; set; }
            public string Code { get; set; }

            public CountryInfo(string name, string code)
            {
                Name = name;
                Code = code;
            }
        }

        static readonly Dictionary<string, CountryInfo> CountriesMap = new Dictionary<string, CountryInfo>
        {
            { "AFN", new CountryInfo("Afghanistan", "AF") },
            { "AFA", new CountryInfo("Afghanistan", "AF") },
            { "ALK", new CountryInfo("Albania", "AL") },
            { "ALL", new CountryInfo("Albania", "AL") },
            { "DZD", new CountryInfo("Algeria", "DZ") },
            { "USD", new CountryInfo("American Samoa", "AS") },
            { "ADF", new CountryInfo("Andorra", "AD") },
            { "ADP", new CountryInfo("Andorra", "AD") },
            { "EUR", new CountryInfo("Andorra", "AD") },
            { "AOR", new CountryInfo("Angola", "AO") },
            { "AON", new CountryInfo("Angola", "AO") },
            { "AOA", new CountryInfo("Angola", "AO") },
            { "XCD", new CountryInfo("Anguilla", "AI") },
            { "ARA", new CountryInfo("Argentina", "AR") },
            { "ARS", new CountryInfo("Argentina", "AR") },
            { "ARL", new CountryInfo("Argentina", "AR") },
            { "ARM", new CountryInfo("Argentina", "AR") },
            { "ARP", new CountryInfo("Argentina", "AR") },
            { "AMD", new CountryInfo("Armenia", "AM") },
            { "AWG", new CountryInfo("Aruba", "AW") },
            { "AUD", new CountryInfo("Australia", "AU") },
            { "ATS", new CountryInfo("Austria", "AT") },
            { "AZM", new CountryInfo("Azerbaijan", "AZ") },
            { "AZN", new CountryInfo("Azerbaijan", "AZ") },
            { "BSD", new CountryInfo("Bahamas", "BS") },
            { "BHD", new CountryInfo("Bahrain", "BH") },
            { "BDT", new CountryInfo("Bangladesh", "BD") },
            { "BBD", new CountryInfo("Barbados", "BB") },
            { "BYR", new CountryInfo("Belarus", "BY") },
            { "BEC", new CountryInfo("Belgium", "BE") },
            { "BEF", new CountryInfo("Belgium", "BE") },
            { "BEL", new CountryInfo("Belgium", "BE") },
            { "BZD", new CountryInfo("Belize", "BZ") },
            { "XOF", new CountryInfo("Benin", "BJ") },
            { "BMD", new CountryInfo("Bermuda", "BM") },
            { "INR", new CountryInfo("Bhutan", "BT") },
            { "BTN", new CountryInfo("Bhutan", "BT") },
            { "BOP", new CountryInfo("Bolivia, Plurinational State Of", "BO") },
            { "BOB", new CountryInfo("Bolivia, Plurinational State Of", "BO") },
            { "BOV", new CountryInfo("Bolivia, Plurinational State Of", "BO") },
            { "BAM", new CountryInfo("Bosnia and Herzegovina", "BA") },
            { "BWP", new CountryInfo("Botswana", "BW") },
            { "NOK", new CountryInfo("Bouvet Island", "BV") },
            { "BRC", new CountryInfo("Brazil", "BR") },
            { "BRB", new CountryInfo("Brazil", "BR") },
            { "BRL", new CountryInfo("Brazil", "BR") },
            { "BND", new CountryInfo("Brunei Darussalam", "BN") },
            { "BGN", new CountryInfo("Bulgaria", "BG") },
            { "BGJ", new CountryInfo("Bulgaria", "BG") },
            { "BGK", new CountryInfo("Bulgaria", "BG") },
            { "BGL", new CountryInfo("Bulgaria", "BG") },
            { "BIF", new CountryInfo("Burundi", "BI") },
            { "KHR", new CountryInfo("Cambodia", "KH") },
            { "XAF", new CountryInfo("Cameroon", "CM") },
            { "CAD", new CountryInfo("Canada", "CA") },
            { "CVE", new CountryInfo("Cape Verde", "CV") },
            { "KYD", new CountryInfo("Cayman Islands", "KY") },
            { "CLP", new CountryInfo("Chile", "CL") },
            { "CLF", new CountryInfo("Chile", "CL") },
            { "CNX", new CountryInfo("China", "CN") },
            { "CNY", new CountryInfo("China", "CN") },
            { "COP", new CountryInfo("Colombia", "CO") },
            { "COU", new CountryInfo("Colombia", "CO") },
            { "KMF", new CountryInfo("Comoros", "KM") },
            { "CDF", new CountryInfo("Congo, The Democratic Republic Of The", "CD") },
            { "NZD", new CountryInfo("Cook Islands", "CK") },
            { "CRC", new CountryInfo("Costa Rica", "CR") },
            { "HRK", new CountryInfo("Croatia", "HR") },
            { "CUP", new CountryInfo("Cuba", "CU") },
            { "CUC", new CountryInfo("Cuba", "CU") },
            { "ANG", new CountryInfo("Curaçao", "CW") },
            { "CYP", new CountryInfo("Cyprus", "CY") },
            { "CZK", new CountryInfo("Czech Republic", "CZ") },
            { "CSK", new CountryInfo("Czechoslovak Socialist Republic", "CS") },
            { "CSJ", new CountryInfo("Czechoslovak Socialist Republic", "CS") },
            { "DKK", new CountryInfo("Denmark", "DK") },
            { "DJF", new CountryInfo("Djibouti", "DJ") },
            { "DOP", new CountryInfo("Dominican Republic", "DO") },
            { "ECS", new CountryInfo("Ecuador", "EC") },
            { "EGP", new CountryInfo("Egypt", "EG") },
            { "SVC", new CountryInfo("El Salvador", "SV") },
            { "EQE", new CountryInfo("Equatorial Guinea", "GQ") },
            { "ERN", new CountryInfo("Eritrea", "ER") },
            { "EEK", new CountryInfo("Estonia", "EE") },
            { "ETB", new CountryInfo("Ethiopia", "ET") },
            { "FKP", new CountryInfo("Falkland Islands  (Malvinas)", "FK") },
            { "FJD", new CountryInfo("Fiji", "FJ") },
            { "FIM", new CountryInfo("Finland", "FI") },
            { "FRF", new CountryInfo("France", "FR") },
            { "XFO", new CountryInfo("France", "FR") },
            { "XPF", new CountryInfo("French Polynesia", "PF") },
            { "GMD", new CountryInfo("Gambia", "GM") },
            { "GEL", new CountryInfo("Georgia", "GE") },
            { "DDM", new CountryInfo("German Democratic Republic", "DD") },
            { "DEM", new CountryInfo("Germany", "DE") },
            { "GHS", new CountryInfo("Ghana", "GH") },
            { "GHC", new CountryInfo("Ghana", "GH") },
            { "GIP", new CountryInfo("Gibraltar", "GI") },
            { "GRD", new CountryInfo("Greece", "GR") },
            { "GTQ", new CountryInfo("Guatemala", "GT") },
            { "GBP", new CountryInfo("Guernsey", "GG") },
            { "GNF", new CountryInfo("Guinea", "GN") },
            { "GNE", new CountryInfo("Guinea", "GN") },
            { "GWP", new CountryInfo("Guinea-Bissau", "GW") },
            { "GYD", new CountryInfo("Guyana", "GY") },
            { "HTG", new CountryInfo("Haiti", "HT") },
            { "HNL", new CountryInfo("Honduras", "HN") },
            { "HKD", new CountryInfo("Hong Kong", "HK") },
            { "HUF", new CountryInfo("Hungary", "HU") },
            { "ISK", new CountryInfo("Iceland", "IS") },
            { "ISJ", new CountryInfo("Iceland", "IS") },
            { "IDR", new CountryInfo("Indonesia", "ID") },
            { "IRR", new CountryInfo("Iran, Islamic Republic Of", "IR") },
            { "IQD", new CountryInfo("Iraq", "IQ") },
            { "IEP", new CountryInfo("Ireland", "IE") },
            { "ILP", new CountryInfo("Israel", "IL") },
            { "ILR", new CountryInfo("Israel", "IL") },
            { "ILS", new CountryInfo("Israel", "IL") },
            { "ITL", new CountryInfo("Italy", "IT") },
            { "JMD", new CountryInfo("Jamaica", "JM") },
            { "JPY", new CountryInfo("Japan", "JP") },
            { "JOD", new CountryInfo("Jordan", "JO") },
            { "KZT", new CountryInfo("Kazakhstan", "KZ") },
            { "KES", new CountryInfo("Kenya", "KE") },
            { "KPW", new CountryInfo("Korea, Democratic People\'s Republic Of", "KP") },
            { "KRW", new CountryInfo("Korea, Republic of", "KR") },
            { "KWD", new CountryInfo("Kuwait", "KW") },
            { "KGS", new CountryInfo("Kyrgyzstan", "KG") },
            { "LAK", new CountryInfo("Lao People\'s Democratic Republic", "LA") },
            { "LAJ", new CountryInfo("Lao People\'s Democratic Republic", "LA") },
            { "LVL", new CountryInfo("Latvia", "LV") },
            { "LBP", new CountryInfo("Lebanon", "LB") },
            { "LSL", new CountryInfo("Lesotho", "LS") },
            { "ZAR", new CountryInfo("Lesotho", "LS") },
            { "LRD", new CountryInfo("Liberia", "LR") },
            { "LYD", new CountryInfo("Libya", "LY") },
            { "CHF", new CountryInfo("Liechtenstein", "LI") },
            { "LTL", new CountryInfo("Lithuania", "LT") },
            { "LUF", new CountryInfo("Luxembourg", "LU") },
            { "MOP", new CountryInfo("Macao", "MO") },
            { "MKD", new CountryInfo("Macedonia, the Former Yugoslav Republic Of", "MK") },
            { "MKN", new CountryInfo("Macedonia, the Former Yugoslav Republic Of", "MK") },
            { "MGA", new CountryInfo("Madagascar", "MG") },
            { "MGF", new CountryInfo("Madagascar", "MG") },
            { "MWK", new CountryInfo("Malawi", "MW") },
            { "MYR", new CountryInfo("Malaysia", "MY") },
            { "MVQ", new CountryInfo("Maldives", "MV") },
            { "MVR", new CountryInfo("Maldives", "MV") },
            { "MAF", new CountryInfo("Mali", "ML") },
            { "MTL", new CountryInfo("Malta", "MT") },
            { "MRO", new CountryInfo("Mauritania", "MR") },
            { "MUR", new CountryInfo("Mauritius", "MU") },
            { "MXP", new CountryInfo("Mexico", "MX") },
            { "MXN", new CountryInfo("Mexico", "MX") },
            { "MXV", new CountryInfo("Mexico", "MX") },
            { "MDL", new CountryInfo("Moldova, Republic of", "MD") },
            { "MCF", new CountryInfo("Monaco", "MC") },
            { "MNT", new CountryInfo("Mongolia", "MN") },
            { "MAD", new CountryInfo("Morocco", "MA") },
            { "MZM", new CountryInfo("Mozambique", "MZ") },
            { "MZN", new CountryInfo("Mozambique", "MZ") },
            { "MMK", new CountryInfo("Myanmar", "MM") },
            { "NAD", new CountryInfo("Namibia", "NA") },
            { "NPR", new CountryInfo("Nepal", "NP") },
            { "NLG", new CountryInfo("Netherlands", "NL") },
            { "NIO", new CountryInfo("Nicaragua", "NI") },
            { "NGN", new CountryInfo("Nigeria", "NG") },
            { "OMR", new CountryInfo("Oman", "OM") },
            { "PKR", new CountryInfo("Pakistan", "PK") },
            { "PAB", new CountryInfo("Panama", "PA") },
            { "PGK", new CountryInfo("Papua New Guinea", "PG") },
            { "PYG", new CountryInfo("Paraguay", "PY") },
            { "YDD", new CountryInfo("People\'s Democratic Republic of Yemen", "YD") },
            { "PEN", new CountryInfo("Peru", "PE") },
            { "PEI", new CountryInfo("Peru", "PE") },
            { "PEH", new CountryInfo("Peru", "PE") },
            { "PHP", new CountryInfo("Philippines", "PH") },
            { "PLZ", new CountryInfo("Poland", "PL") },
            { "PLN", new CountryInfo("Poland", "PL") },
            { "PTE", new CountryInfo("Portugal", "PT") },
            { "TPE", new CountryInfo("Portugal", "PT") },
            { "QAR", new CountryInfo("Qatar", "QA") },
            { "RON", new CountryInfo("Romania", "RO") },
            { "ROL", new CountryInfo("Romania", "RO") },
            { "ROK", new CountryInfo("Romania", "RO") },
            { "RUB", new CountryInfo("Russian Federation", "RU") },
            { "RWF", new CountryInfo("Rwanda", "RW") },
            { "SHP", new CountryInfo("Saint Helena, Ascension and Tristan Da Cunha", "SH") },
            { "WST", new CountryInfo("Samoa", "WS") },
            { "STD", new CountryInfo("Sao Tome and Principe", "ST") },
            { "SAR", new CountryInfo("Saudi Arabia", "SA") },
            { "CSD", new CountryInfo("Serbia", "RS") },
            { "RSD", new CountryInfo("Serbia", "RS") },
            { "SCR", new CountryInfo("Seychelles", "SC") },
            { "SLL", new CountryInfo("Sierra Leone", "SL") },
            { "SGD", new CountryInfo("Singapore", "SG") },
            { "SKK", new CountryInfo("Slovakia", "SK") },
            { "SIT", new CountryInfo("Slovenia", "SI") },
            { "SBD", new CountryInfo("Solomon Islands", "SB") },
            { "SOS", new CountryInfo("Somalia", "SO") },
            { "ZAL", new CountryInfo("South Africa", "ZA") },
            { "SSP", new CountryInfo("South Sudan", "SS") },
            { "ESP", new CountryInfo("Spain", "ES") },
            { "ESA", new CountryInfo("Spain", "ES") },
            { "ESB", new CountryInfo("Spain", "ES") },
            { "LKR", new CountryInfo("Sri Lanka", "LK") },
            { "SDD", new CountryInfo("Sudan", "SD") },
            { "SDG", new CountryInfo("Sudan", "SD") },
            { "SDP", new CountryInfo("Sudan", "SD") },
            { "SRD", new CountryInfo("Suriname", "SR") },
            { "SRG", new CountryInfo("Suriname", "SR") },
            { "SZL", new CountryInfo("Swaziland", "SZ") },
            { "SEK", new CountryInfo("Sweden", "SE") },
            { "CHE", new CountryInfo("Switzerland", "CH") },
            { "CHW", new CountryInfo("Switzerland", "CH") },
            { "SYP", new CountryInfo("Syrian Arab Republic", "SY") },
            { "TWD", new CountryInfo("Taiwan, Province Of China", "TW") },
            { "TJS", new CountryInfo("Tajikistan", "TJ") },
            { "TJR", new CountryInfo("Tajikistan", "TJ") },
            { "TZS", new CountryInfo("Tanzania, United Republic of", "TZ") },
            { "THB", new CountryInfo("Thailand", "TH") },
            { "TOP", new CountryInfo("Tonga", "TO") },
            { "TTD", new CountryInfo("Trinidad and Tobago", "TT") },
            { "TND", new CountryInfo("Tunisia", "TN") },
            { "TRY", new CountryInfo("Turkey", "TR") },
            { "TRL", new CountryInfo("Turkey", "TR") },
            { "TMM", new CountryInfo("Turkmenistan", "TM") },
            { "TMT", new CountryInfo("Turkmenistan", "TM") },
            { "RUR", new CountryInfo("U.S.S.R.", "SU") },
            { "SUR", new CountryInfo("U.S.S.R.", "SU") },
            { "UGX", new CountryInfo("Uganda", "UG") },
            { "UGS", new CountryInfo("Uganda", "UG") },
            { "UAH", new CountryInfo("Ukraine", "UA") },
            { "UAK", new CountryInfo("Ukraine", "UA") },
            { "AED", new CountryInfo("United Arab Emirates", "AE") },
            { "USN", new CountryInfo("United States", "US") },
            { "USS", new CountryInfo("United States", "US") },
            { "UYU", new CountryInfo("Uruguay", "UY") },
            { "UYN", new CountryInfo("Uruguay", "UY") },
            { "UYI", new CountryInfo("Uruguay", "UY") },
            { "UZS", new CountryInfo("Uzbekistan", "UZ") },
            { "VUV", new CountryInfo("Vanuatu", "VU") },
            { "VEF", new CountryInfo("Venezuela, Bolivarian Republic of", "VE") },
            { "VEB", new CountryInfo("Venezuela, Bolivarian Republic of", "VE") },
            { "VND", new CountryInfo("Viet Nam", "VN") },
            { "VNC", new CountryInfo("Viet Nam", "VN") },
            { "YER", new CountryInfo("Yemen", "YE") },
            { "YUD", new CountryInfo("Yugoslavia", "YU") },
            { "YUM", new CountryInfo("Yugoslavia", "YU") },
            { "ZRN", new CountryInfo("Zaire", "ZR") },
            { "ZRZ", new CountryInfo("Zaire", "ZR") },
            { "ZMK", new CountryInfo("Zambia", "ZM") },
            { "ZWL", new CountryInfo("Zimbabwe", "ZW") },
            { "ZWD", new CountryInfo("Zimbabwe", "ZW") },
            { "ZWC", new CountryInfo("Zimbabwe", "ZW") }
        };

        public string Name
        {
            get { return CountriesMap.ContainsKey(Code) ? CountriesMap[Code].Name : Code; }
        }

        public string CountryCode
        {
            get { return CountriesMap.ContainsKey(Code) ? CountriesMap[Code].Code : null; }
        }
    }
}

